<a href="https://colab.research.google.com/github/Gabuni19/GabUni--Codigos-cpp/blob/main/MetodoSimplex.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Metodo Simplex

**maximizar  :** F(X) \\
**sujeto a   :**  E1(X),E2(X), .... En(X)

In [56]:
import numpy as np
from tabulate import tabulate

#Definimos la funcion objetivo
F = np.array([3,1,3])
#Definimos las ecuaciones
E =np.array( [ [2,1,1,2] , [1,2,3,5] ,[2,2,1,6] ] )


def MetodoSimplex(F,E):
  #Calculamos variables auxiliares
  n_variables = np.shape(F)[0]
  n_ecuaciones =  np.shape(E)[0]
  print("Numero de variables: {}".format(n_variables))
  print("Numero de ecuaciones: {}\n".format(n_ecuaciones))

  #Creamos el arreglo que contiene el indice de las variables de la columna r
  indice_var = np.array([-1 for i  in range(n_variables)])
  print(indice_var)
  # Paso1 :Creacion de la matriz
  n_filas = n_ecuaciones+1
  n_columnas =  (n_variables)*2+2
  M = np.zeros((n_filas,n_columnas))

  # Paso 2 : Rellenamos la matriz
  # 1) Rellanamos la ultima fila
  M[-1,0]=1
  M[-1,1:n_variables+1] = F*(-1)


  # 2) Rellenamos las demas filas
  for i in range(n_ecuaciones):
    M[i,1:n_variables+1] = E[i,:n_variables] #Rellenando las variables no basicas
    M[i,-1] = E[i,-1] #Rellenando resultado
    M[i,n_variables+1+i]=1 #Rellenamos la diagonal 1

  # Establecer opciones de impresión para NumPy
  np.set_printoptions(precision=4, suppress=True)

  print(tabulate([[M]],headers = ["Matriz Simplex"], tablefmt="grid"))


  while True :
    # Paso 3 : Seleccionamos de la fila z la columna q
    fila_z  = M[-1,1:n_variables+1]

    mayor=-1
    columna_q =0
    for i in range(n_variables):
      if(fila_z[i]<0 and abs(fila_z[i])>mayor):
        mayor=i
        columna_q=i+1

    print(tabulate([[fila_z,fila_z[columna_q-1],columna_q]],headers = ["Fila z (NO BASICA)","Mayor","Columna Escogida"], tablefmt="grid"))

    # Paso 4 : Calcula las razones
    fila_resultado = M[:n_ecuaciones,-1] / M[:n_ecuaciones,columna_q]

    aiq = M[:n_ecuaciones,columna_q]

    no_acotado = True
    for a in aiq:
      if a > 0:
        no_acotado = False


    if(no_acotado):
      print(" [-] El problema no esta acotado.")
      break

    # Paso 5 :Se elige la menor razon positiva
    menor =99999
    fila_q=0
    for i in range(len(fila_resultado)):
      if(fila_resultado[i]>0 and fila_resultado[i]<menor):
        menor = fila_resultado[i]
        fila_q=i

    #Asignamos un valor al arreglo de indices
    indice_var[fila_q] = columna_q

    print(tabulate([[fila_resultado,fila_resultado[fila_q],fila_q]],headers = ["Fila Razones (bi/aiq)","Menor","Fila Escogida"], tablefmt="grid"))

    # Paso 6 : Seleccionamos el pivote
    pivote = M[fila_q,columna_q]
    print("\n -> Pivote: {}".format(pivote))

    # Paso 7 : Aplicamos operaciones elementales
    # Hacemos 1 el pivote
    for i in range(n_columnas):
      M[fila_q,i] /= pivote

    pivote = M[fila_q,columna_q]

    print(" -> (Fila {}) / pivote".format(fila_q))
    print(" -> Nuevo pivote : {}".format(pivote))
    print(tabulate([[M]],headers = ["Matriz Simplex"], tablefmt="grid"))

    print(" [+] Hacemos 0 la (Columna {})".format(columna_q))
    # y hacemos 0 la columna q
    for i in range(n_filas):
      if i != fila_q:
        factor = -M[i,columna_q]
        for j in range(n_columnas):
          M[i,j] = M[i,j] + factor*M[fila_q,j]

    print(tabulate([[M]],headers = ["Matriz Simplex"], tablefmt="grid"))

    # Paso 8 : Si todos los coeficientes de la fila z en cuyas columnas estan
    # x1, x2, , xn son positivas o ceros, se para. Sino se regresa al paso 3 y se
    # repite el proceso.
    if all(x >= 0 for x in M[-1, 1:n_variables + 1]):
            break

  print(tabulate([[M]],headers = ["Matriz Simplex"], tablefmt="grid"))

  columna_r =  M[:,-1]

  print(" Arreglo indices:",indice_var)
  k=0
  for i in indice_var:
    if i!=-1:
      print(" -> x{} = {}".format(i,columna_r[k]))
      k+=1
    else:
      print(" -> x{} = {}".format(k,0))



  print(" [+] Maximo Valor =  {}".format(columna_r[-1]))

MetodoSimplex(F,E)

Numero de variables: 3
Numero de ecuaciones: 3

[-1 -1 -1]
+-------------------------------------+
| Matriz Simplex                      |
+=====================================+
| [[ 0.  2.  1.  1.  1.  0.  0.  2.]  |
|  [ 0.  1.  2.  3.  0.  1.  0.  5.]  |
|  [ 0.  2.  2.  1.  0.  0.  1.  6.]  |
|  [ 1. -3. -1. -3.  0.  0.  0.  0.]] |
+-------------------------------------+
+----------------------+---------+--------------------+
| Fila z (NO BASICA)   |   Mayor |   Columna Escogida |
+======================+=========+====================+
| [-3. -1. -3.]        |      -3 |                  3 |
+----------------------+---------+--------------------+
+-------------------------+---------+-----------------+
| Fila Razones (bi/aiq)   |   Menor |   Fila Escogida |
+=========================+=========+=================+
| [2.     1.6667 6.    ]  | 1.66667 |               1 |
+-------------------------+---------+-----------------+

 -> Pivote: 3.0
 -> (Fila 1) / pivote
 -> Nuevo pivote : 1.0

In [ ]:
print(E[-1,0])

7


array([7, 9])