<a href="https://colab.research.google.com/github/Gabuni19/GabUni--Codigos-cpp/blob/main/Analisis%20y%20Modelamiento%20Num%C3%A9rico%20I/Metodos_Numericos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Funcion Normalizar

In [ ]:
def normalizar(x):
    """Funcion que nomarliza un valor x ala forma : 0.[...]e[...]
    
        Parametros posicionales:
        x -- numero a normalizar entero
    """
    #Creamos un variable que indique si es positivo
    positivo=1    
    #Si x es un numero negativo pasarlo a positivo
    if x<0:
        x=abs(x)
        positivo=-1;
    
    if x==0: 
        return (0,0);
    elif (x>1):
        t=len(str(int(x)))
        x=x/10**t
        return (positivo*x,10**t)
    else:
        t=len(str(x).split(".")[-1])        
        aux=x*10**t        
        m=len(str(int(aux)))
        x=x*10**(t-m)
        return (positivo*x,10**-(t-m))

Retorna una dupla : (numero de la forma 0.algo ,factor multiplo de 10)

In [ ]:
normalizar(12.45)

(0.1245, 100)

In [ ]:
normalizar(11111.45456)

(0.1111145456, 100000)

In [ ]:
normalizar(0.23333)

(0.23333, 1)

## Funcion Flotante (Usa Normalizar)

In [ ]:
def normalizar(x):
    """Funcion que nomarliza un valor x ala forma : 0.[...]e[...]
    
        Parametros posicionales:
        x -- numero a normalizar
    """
    #Creamos un variable que indique si es positivo
    positivo=1    
    #Si x es un numero negativo pasarlo a positivo
    if x<0:
        x=abs(x)
        positivo=-1;
    
    if x==0: 
        return (0,0);
    elif (x>1):
        t=len(str(int(x)))
        x=x/10**t
        return (positivo*x,10**t)
    else:
        t=len(str(x).split(".")[-1])        
        aux=x*10**t        
        m=len(str(int(aux)))
        x=x*10**(t-m)
        return (positivo*x,10**-(t-m))
      
def fl(x,decimales):
    """Funcion que calcula el fl(x) de un numero x
    
        Parametros posicionales:
        x -- numero real
        decimales -- decimales a redondear
    """
    (d,potencia)=normalizar(x)
    d = round(d,decimales)
    return (d,potencia)

Retorna una dupla :(decimal normalizado y redondeado,potencia de 10)

In [ ]:
fl(0.5744531,2)

(0.57, 1)

In [ ]:
fl(24.5744531,5)

(0.24574, 100)

## Binario a Decimal (Descomposicion polinomica)

In [ ]:
def Binario_Decimal(numero):
    """Funcion que transforma un numero binario a decimal
    
        Parametros posicionales:
        numero -- numero en tipo string    
    """
    d=0
    if "." in numero :
        (entero,decimal)= numero.split(".")
        n = len(entero)        
        for i in range(n):
            d+=int(entero[i])*(2**(n-i-1))
        m = len(decimal)
        for i in range(m):
            d+=int(decimal[i])*(2**-(i+1))
        return d                
    else:        
        n = len(numero)        
        for i in range(n):
            d+=int(numero[i])*(2**(n-i-1))
        return d 

In [ ]:
Binario_Decimal("1.011")

1.375

In [ ]:
Binario_Decimal("0.1")

0.5

## Rango  de Complemento a 2

In [ ]:
from tabulate import tabulate

def Rango_Representacion(n): 
    header =["n","Positivos","Negativos"]
    datos=[]
    columna=[]
    for n in range(4,n):
        columna.append(n)
        datos.append([n,[0,2**(n-1)-1],[-1,-(2**(n-1))]])
    print(tabulate(datos, header))

Retorna una tabla de los numeros que se pueden representar segun la longitud de palabra con la que se esta trabajando (n)

In [ ]:
Rango_Representacion(15)

  n  Positivos    Negativos
---  -----------  -----------
  4  [0, 7]       [-1, -8]
  5  [0, 15]      [-1, -16]
  6  [0, 31]      [-1, -32]
  7  [0, 63]      [-1, -64]
  8  [0, 127]     [-1, -128]
  9  [0, 255]     [-1, -256]
 10  [0, 511]     [-1, -512]
 11  [0, 1023]    [-1, -1024]
 12  [0, 2047]    [-1, -2048]
 13  [0, 4095]    [-1, -4096]
 14  [0, 8191]    [-1, -8192]


## Numero a Complemento a 2

In [ ]:
def To_complemento2(numero , bits ):
    """Funcion que pasa un numero entero a su complemento a 2 en
       en binario a partir de una longitud de palabra (bits).
       
       Parametros Posicionales:
       numero -- entero que se desea pasar a complemento a 2 (int)
       bits -- longitud de palabra con la que se trabaja
    
    """
    if(numero >= 0):
        if(numero<=2**(bits-1)-1):            
            b = bin(numero)[2:]     # Almacena el binario de "numero" en b        
            b = b.rjust(bits,"0")   # completa los bits con cero
            return b
        else:
            print("No se puede representar {}>{}.".format(numero,2**(bits-1)-1))
            return -1
    else:
        
        aux = abs(numero)
        if(aux<=(2**(bits-1))):            
            c2 = 2**bits - aux
            c2 = bin(c2)[2:]              
            return c2
        else:
            print("No se puede representar {}>{}.".format(aux,2**(bits-1)))
            return -1

In [ ]:
To_complemento2(34,8)

'00100010'

## Eliminacion Gauseana

In [ ]:
import numpy as np
from tabulate import tabulate

def ElementalC_Fij(n, i, j):
    E = np.eye(n)
    E[i,i], E[j,j] = 0, 0
    E[i,j], E[j,i] = 1, 1
    return E

def Elemental_Fi(n, i, k):
    E = np.eye(n)
    E[i,i] = k
    return E

def Elemental_Fij(n, i, j, k):
    E = np.eye(n)
    E[i,j] = k
    return E 

def findCero(A,i,j):
    p = -1
    for f in range(i,j):
        if (A[f][i-1]!=0):
            p = f
            break
    return p

def SustRegresiva(U,b):
    # Verificar si es triangular superior y cuadrado
    m,n = U.shape
    if m!=n:
        print("Proceso de Sustitucion Regresiva ERROR-[ Matriz no cuadrada ] ")
        return
    if np.array_equal(A, np.triu(A)):
        print("Proceso de Sustitucion Regresiva ERROR-[ Matriz no triangular superior ] ")
        return
    x = np.zeros(m)
    for i in range(m-1,-1,-1):
        suma = 0
        for j in range(i+1,n):
            suma += U[i][j]*x[j]
        x[i] = (b[i] - suma) / U[i][i]
    return x

def EliminacionGaussiana(A,b):
    m,n = A.shape
    M = np.concatenate((A,b), axis = 1 )
    E = [[A,b,M]]
    print(tabulate(E,headers=[["MATRIZ A"],["MATRIZ b"],["MATRIZ AUMENTADA"]],tablefmt='grid'))

    print("\t[+] ELIMINACION GAUSSEANA\n")       
    for i in range(m-1):
        pivote = M[i][i]
        print("Paso 1 : Hallando el pivote !=0")
        print("\t [+]Pivote   : {}".format(pivote))
        print("\t [+]Posicion : ({},{})".format(i,i))
        if pivote == 0:
            print("\t[-] Cambio de filas.")
            p = findCero(M,i+1,n) # Fila del nuevo pivote !=0
            if p == -1:
                print("No se encontro pivote Nulo.")
                return
            else:
                print("\t [+] Nuevo pivote: {}".format(M[p][i]))
                print("\t [+] Posicion : ({},{})".format(p,i))
                Fip = ElementalC_Fij(m,i,p)
                M_aux=M
                M = np.dot(Fip,M)
                pivote = M[i][i]
                h = ["Fip","M","Fip x M"]
                E = [[Fip,M_aux,M]]
                print(tabulate(E,headers=h,tablefmt='grid'))
                
        # Si no es diferente de cero Hacemos cero la columna
        print("Paso 2 : Las matrices elementales")
        header = ["Matriz Aumentada"]
        c=1
        E = [[M]]
        for j in range(i+1,m):
            factor = M[j][i]/pivote
            Fji = Elemental_Fij(m,j,i,-factor)            
            E[0].insert(0,np.copy(Fji))
            header.insert(0,"E"+str(c)+": F_{}{}({})".format(j,i,-factor))
            c+=1
            M = np.dot(Fji,M)
            
        print(tabulate(E,headers=header,tablefmt='grid'))
        print("Paso 3 : Haciendo (0) la columna C[{}]".format(i))
        print(M,"\n\n")
        
            
    U = M[:,:-1]
    b = M[:,-1:]
    x = SustRegresiva(U,b)
    h = ["U","b","Conjunto Solucion"]
    E = [[U,b,x.reshape(m,1)]]
    print("\t -> Por Sustitucion Regresiva")
    print(tabulate(E,headers=h,tablefmt='grid'))


In [ ]:
import numpy as np
A = np.array([
            [-1,3,-1,1],
            [1,-1,2,-1],
            [3,1,-2,2],
            [3,-1,1,2]
])
b = np.array([ 
                [-8],
                [4],
                [4],
                [16]
])
EliminacionGaussiana(A,b)

+-----------------+----------------+------------------------+
| ['MATRIZ A']    | ['MATRIZ b']   | ['MATRIZ AUMENTADA']   |
+=================+================+========================+
| [[-1  3 -1  1]  | [[-8]          | [[-1  3 -1  1 -8]      |
|  [ 1 -1  2 -1]  |  [ 4]          |  [ 1 -1  2 -1  4]      |
|  [ 3  1 -2  2]  |  [ 4]          |  [ 3  1 -2  2  4]      |
|  [ 3 -1  1  2]] |  [16]]         |  [ 3 -1  1  2 16]]     |
+-----------------+----------------+------------------------+
	[+] ELIMINACION GAUSSEANA

Paso 1 : Hallando el pivote !=0
	 [+]Pivote   : -1
	 [+]Posicion : (0,0)
Paso 2 : Las matrices elementales
+-----------------+-----------------+-----------------+--------------------+
| E3: F_30(3.0)   | E2: F_20(3.0)   | E1: F_10(1.0)   | Matriz Aumentada   |
+=================+=================+=================+====================+
| [[1. 0. 0. 0.]  | [[1. 0. 0. 0.]  | [[1. 0. 0. 0.]  | [[-1  3 -1  1 -8]  |
|  [0. 1. 0. 0.]  |  [0. 1. 0. 0.]  |  [1. 1. 0. 0.]  |  [ 1 

Metodo de Gaus Jordan

In [ ]:
import numpy as np
from tabulate import tabulate

def ElementalC_Fij(n, i, j):
    E = np.eye(n)
    E[i,i], E[j,j] = 0, 0
    E[i,j], E[j,i] = 1, 1
    return E

def Elemental_Fi(n, i, k):
    E = np.eye(n)
    E[i,i] = k
    return E

def Elemental_Fij(n, i, j, k):
    E = np.eye(n)
    E[i,j] = k
    return E 

def findCero(A,i,j):
    p = -1
    for f in range(i,j):
        if (A[f][i-1]!=0):
            p = f
            break
    return p

def SustRegresiva(U,b):
    # Verificar si es triangular superior y cuadrado
    m,n = U.shape
    if m!=n:
        print("Proceso de Sustitucion Regresiva ERROR-[ Matriz no cuadrada ] ")
        return
    if np.array_equal(A, np.triu(A)):
        print("Proceso de Sustitucion Regresiva ERROR-[ Matriz no triangular superior ] ")
        return
    x = np.zeros(m)
    for i in range(m-1,-1,-1):
        suma = 0
        for j in range(i+1,n):
            suma += U[i][j]*x[j]
        x[i] = (b[i] - suma) / U[i][i]
    return x

def EliminacionGaussJordan(A,b):
    m,n = A.shape
    M = np.concatenate((A,b), axis = 1 )
    E = [[A,b,M]]
    print(tabulate(E,headers=[["MATRIZ A"],["MATRIZ b"],["MATRIZ AUMENTADA"]],tablefmt='grid'))

    print("\t[+] ELIMINACION POR GAUSS JORDAN\n")       
    for i in range(m):        
        pivote = M[i][i]
        print("Paso 1 : Hallando el pivote !=0")
        print("\t [+]Pivote   : {}".format(pivote))
        print("\t [+]Posicion : ({},{})".format(i,i))
        if pivote == 0:
            print("\t[-] Cambio de filas.")
            p = findCero(M,i+1,n) # Fila del nuevo pivote !=0
            if p == -1:
                print("No se encontro pivote Nulo.")
                return
            else:
                print("\t [+] Nuevo pivote: {}".format(M[p][i]))
                print("\t [+] Posicion : ({},{})".format(p,i))
                Fip = ElementalC_Fij(m,i,p)
                M_aux=M
                M = np.dot(Fip,M)
                pivote = M[i][i]
                h = ["Fip","M","Fip x M"]
                E = [[Fip,M_aux,M]]
                print(tabulate(E,headers=h,tablefmt='grid'))
        
        # luego tenemos que hacer 1 al pivote
        print("\t Luego Haciendo 1 al pivote : ")
        Fi = Elemental_Fi(m,i,1/pivote)
        M_aux=M
        M = np.dot(Fi,M)
        pivote = M[i][i]
        h = ["Fi","M","Fi x M"]
        E = [[Fi,M_aux,M]]
        print(tabulate(E,headers=h,tablefmt='grid'))
        
        
        # Si no es diferente de cero Hacemos cero la columna
        print("Paso 2 : Las matrices elementales")
        header = ["Matriz Aumentada"]
        c=1
        E = [[M]]
        for j in range(i+1,m):
            factor = M[j][i]/pivote
            Fji = Elemental_Fij(m,j,i,-factor)            
            E[0].insert(0,np.copy(Fji))
            header.insert(0,"E"+str(c)+": F_{}{}({})".format(j,i,-factor))
            c+=1
            M = np.dot(Fji,M)
        for j in range(i):
            factor = M[j][i]/pivote
            Fji = Elemental_Fij(m,j,i,-factor)            
            E[0].insert(0,np.copy(Fji))
            header.insert(0,"E"+str(c)+": F_{}{}({})".format(j,i,-factor))
            c+=1
            M = np.dot(Fji,M)
            
        
        print(tabulate(E,headers=header,tablefmt='grid'))
        print("Paso 3 : Haciendo (0) la columna C[{}]".format(i))
        print(M,"\n\n") 
                
    
    x = M[:,-1]    
    print("\t -> El conjunto solucion : ")
    print(x.reshape(n,1))
    

In [ ]:
import numpy as np
A = np.array([
            [-1,3,-1,1],
            [1,-1,2,-1],
            [3,1,-2,2],
            [3,-1,1,2]
])
b = np.array([ 
                [-8],
                [4],
                [4],
                [16]
])
EliminacionGaussJordan(A,b)

+-----------------+----------------+------------------------+
| ['MATRIZ A']    | ['MATRIZ b']   | ['MATRIZ AUMENTADA']   |
+=================+================+========================+
| [[-1  3 -1  1]  | [[-8]          | [[-1  3 -1  1 -8]      |
|  [ 1 -1  2 -1]  |  [ 4]          |  [ 1 -1  2 -1  4]      |
|  [ 3  1 -2  2]  |  [ 4]          |  [ 3  1 -2  2  4]      |
|  [ 3 -1  1  2]] |  [16]]         |  [ 3 -1  1  2 16]]     |
+-----------------+----------------+------------------------+
	[+] ELIMINACION POR GAUSS JORDAN

Paso 1 : Hallando el pivote !=0
	 [+]Pivote   : -1
	 [+]Posicion : (0,0)
	 Luego Haciendo 1 al pivote : 
+---------------------+--------------------+-------------------------+
| Fi                  | M                  | Fi x M                  |
+=====================+====================+=========================+
| [[-1.  0.  0.  0.]  | [[-1  3 -1  1 -8]  | [[ 1. -3.  1. -1.  8.]  |
|  [ 0.  1.  0.  0.]  |  [ 1 -1  2 -1  4]  |  [ 1. -1.  2. -1.  4.]  |
|  [ 0.  

## Metodo de Parlet Reid

In [1]:
import numpy as np
from tabulate import tabulate

def e(i,n):
    I=np.identity(n)
    return I[:,i-1:i]


def Fila_maximoElement(sub_matriz):
    n = np.shape(sub_matriz)[0] # Numero de filas
    ind = np.argmax(np.abs(sub_matriz))   
    return ind
        
def Formar_P(n,i_actual,j_maximo):
    I = np.identity(n)
    if(i_actual!=j_maximo):
        colum_actual  = I[:,i_actual:i_actual+1].copy()
        I[:,i_actual:i_actual+1]=I[:,j_maximo:j_maximo+1]
        I[:,j_maximo:j_maximo+1]=colum_actual
        return I
    else:
        return I

def FormarAlpha(Subcolumna):
    m,n = np.shape(Subcolumna)
    f_max = Fila_maximoElement(Subcolumna)   
    maximo = Subcolumna[f_max].copy()
    aux = Subcolumna[0].copy()
    for i in range(m):
        if(Subcolumna[i]==maximo):
            Subcolumna[i]=aux
            Subcolumna[0]=maximo
            break    
    for i in range(m):        
        Subcolumna[i]= Subcolumna[i]/maximo      
    
    return Subcolumna
    
def Formar_M(Subcolumna,i,n):
    I = np.identity(n)
    e = I[i:i+1,:]
    s = np.zeros((n,1))
    s_aux = FormarAlpha(Subcolumna)   
    s[i+1:,:]=s_aux[1:,:]
    
    print(" 3) Generamos M{}: I - alpha.e{}".format(i,i+1))
    print(tabulate([[I,s,e]],headers=["I","alpha","e"], tablefmt='grid')) 
    return I-np.dot(s,e)

def imprimir_titulo(titulo):
    titulo_cent = titulo.center(50)
    print(f"\n{'='*50}\n{titulo_cent}\n{'='*50}")
    
def ParletReit(A):
    imprimir_titulo("Metodo de Parlet Reid")
    n =  np.shape(A)[0]
    print(tabulate([["Matriz A",A]], tablefmt='grid'))  
    for i in range(n-2):
        print(" 1) Evaluamos la subcolumna:")
        Subcolumna = A[i+1:,i:i+1] 
        maximo = Fila_maximoElement(Subcolumna)
        print(tabulate([[A,Subcolumna,A[i,i+maximo+1]]],headers=["A","Subcolumna","maximo"], tablefmt='grid'))  
        P = Formar_P(n,i+1,i+maximo+1)
        print(" 2) Generamos P{}: e{} <-> e{}".format(i+1,i+2,i+maximo+2))
        print(tabulate([["P",P]], tablefmt='grid')) 
        M = Formar_M(Subcolumna.astype(float),i+1,n)
        print(" 4) Generamos M{}:".format(i+1))
        print(tabulate([["M",M]], tablefmt='grid')) 
        print(" 5) Hallamos el MP y MP.T :".format(i+1))
        MP = np.dot(M,P)
        MP_T = MP.T
        print(tabulate([[MP,MP_T]],headers=["MP","MP_T"], tablefmt='grid')) 
        print(" 6) Generamos el nuevo A({}):".format(i+1))
        A_aux=A.copy()
        A_aux = np.dot(MP,A_aux)
        A_aux = np.dot(A_aux,MP_T)
        A=A_aux
        print(tabulate([["MP(A{})MP.T".format(i+1),A]], tablefmt='grid')) 
        print()

In [2]:
A = np.array([
    [5,2,9,-6],
    [2,5,-6,9],
    [9,-6,5,2],
    [-6,9,2,5]
])
ParletReit(A)


              Metodo de Parlet Reid               
+----------+-----------------+
| Matriz A | [[ 5  2  9 -6]  |
|          |  [ 2  5 -6  9]  |
|          |  [ 9 -6  5  2]  |
|          |  [-6  9  2  5]] |
+----------+-----------------+
 1) Evaluamos la subcolumna:
+-----------------+--------------+----------+
| A               | Subcolumna   |   maximo |
+=================+==============+==========+
| [[ 5  2  9 -6]  | [[ 2]        |        9 |
|  [ 2  5 -6  9]  |  [ 9]        |          |
|  [ 9 -6  5  2]  |  [-6]]       |          |
|  [-6  9  2  5]] |              |          |
+-----------------+--------------+----------+
 2) Generamos P1: e2 <-> e3
+---+-----------------+
| P | [[1. 0. 0. 0.]  |
|   |  [0. 0. 1. 0.]  |
|   |  [0. 1. 0. 0.]  |
|   |  [0. 0. 0. 1.]] |
+---+-----------------+
 3) Generamos M1: I - alpha.e2
+-----------------+-----------------+-----------------+
| I               | alpha           | e               |
+=================+=================+=============