<a href="https://colab.research.google.com/github/Gabuni19/GabUni--Codigos-cpp/blob/main/Analisis%20y%20Modelamiento%20Num%C3%A9rico%20I/Metodos_Numericos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Funcion Normalizar

In [ ]:
def normalizar(x):
    """Funcion que nomarliza un valor x ala forma : 0.[...]e[...]
    
        Parametros posicionales:
        x -- numero a normalizar entero
    """
    #Creamos un variable que indique si es positivo
    positivo=1    
    #Si x es un numero negativo pasarlo a positivo
    if x<0:
        x=abs(x)
        positivo=-1;
    
    if x==0: 
        return (0,0);
    elif (x>1):
        t=len(str(int(x)))
        x=x/10**t
        return (positivo*x,10**t)
    else:
        t=len(str(x).split(".")[-1])        
        aux=x*10**t        
        m=len(str(int(aux)))
        x=x*10**(t-m)
        return (positivo*x,10**-(t-m))

Retorna una dupla : (numero de la forma 0.algo ,factor multiplo de 10)

In [ ]:
normalizar(12.45)

(0.1245, 100)

In [ ]:
normalizar(11111.45456)

(0.1111145456, 100000)

In [ ]:
normalizar(0.23333)

(0.23333, 1)

## Funcion Flotante (Usa Normalizar)

In [ ]:
def normalizar(x):
    """Funcion que nomarliza un valor x ala forma : 0.[...]e[...]
    
        Parametros posicionales:
        x -- numero a normalizar
    """
    #Creamos un variable que indique si es positivo
    positivo=1    
    #Si x es un numero negativo pasarlo a positivo
    if x<0:
        x=abs(x)
        positivo=-1;
    
    if x==0: 
        return (0,0);
    elif (x>1):
        t=len(str(int(x)))
        x=x/10**t
        return (positivo*x,10**t)
    else:
        t=len(str(x).split(".")[-1])        
        aux=x*10**t        
        m=len(str(int(aux)))
        x=x*10**(t-m)
        return (positivo*x,10**-(t-m))
      
def fl(x,decimales):
    """Funcion que calcula el fl(x) de un numero x
    
        Parametros posicionales:
        x -- numero real
        decimales -- decimales a redondear
    """
    (d,potencia)=normalizar(x)
    d = round(d,decimales)
    return (d,potencia)

Retorna una dupla :(decimal normalizado y redondeado,potencia de 10)

In [ ]:
fl(0.5744531,2)

(0.57, 1)

In [ ]:
fl(24.5744531,5)

(0.24574, 100)

## Binario a Decimal (Descomposicion polinomica)

In [ ]:
def Binario_Decimal(numero):
    """Funcion que transforma un numero binario a decimal
    
        Parametros posicionales:
        numero -- numero en tipo string    
    """
    d=0
    if "." in numero :
        (entero,decimal)= numero.split(".")
        n = len(entero)        
        for i in range(n):
            d+=int(entero[i])*(2**(n-i-1))
        m = len(decimal)
        for i in range(m):
            d+=int(decimal[i])*(2**-(i+1))
        return d                
    else:        
        n = len(numero)        
        for i in range(n):
            d+=int(numero[i])*(2**(n-i-1))
        return d 

In [ ]:
Binario_Decimal("1.011")

1.375

In [ ]:
Binario_Decimal("0.1")

0.5

## Rango  de Complemento a 2

In [ ]:
from tabulate import tabulate

def Rango_Representacion(n): 
    header =["n","Positivos","Negativos"]
    datos=[]
    columna=[]
    for n in range(4,n):
        columna.append(n)
        datos.append([n,[0,2**(n-1)-1],[-1,-(2**(n-1))]])
    print(tabulate(datos, header))

Retorna una tabla de los numeros que se pueden representar segun la longitud de palabra con la que se esta trabajando (n)

In [ ]:
Rango_Representacion(15)

  n  Positivos    Negativos
---  -----------  -----------
  4  [0, 7]       [-1, -8]
  5  [0, 15]      [-1, -16]
  6  [0, 31]      [-1, -32]
  7  [0, 63]      [-1, -64]
  8  [0, 127]     [-1, -128]
  9  [0, 255]     [-1, -256]
 10  [0, 511]     [-1, -512]
 11  [0, 1023]    [-1, -1024]
 12  [0, 2047]    [-1, -2048]
 13  [0, 4095]    [-1, -4096]
 14  [0, 8191]    [-1, -8192]


## Numero a Complemento a 2

In [ ]:
def To_complemento2(numero , bits ):
    """Funcion que pasa un numero entero a su complemento a 2 en
       en binario a partir de una longitud de palabra (bits).
       
       Parametros Posicionales:
       numero -- entero que se desea pasar a complemento a 2 (int)
       bits -- longitud de palabra con la que se trabaja
    
    """
    if(numero >= 0):
        if(numero<=2**(bits-1)-1):            
            b = bin(numero)[2:]     # Almacena el binario de "numero" en b        
            b = b.rjust(bits,"0")   # completa los bits con cero
            return b
        else:
            print("No se puede representar {}>{}.".format(numero,2**(bits-1)-1))
            return -1
    else:
        
        aux = abs(numero)
        if(aux<=(2**(bits-1))):            
            c2 = 2**bits - aux
            c2 = bin(c2)[2:]              
            return c2
        else:
            print("No se puede representar {}>{}.".format(aux,2**(bits-1)))
            return -1

In [ ]:
To_complemento2(34,8)

'00100010'

## Eliminacion Gauseana

In [ ]:
import numpy as np
from tabulate import tabulate

def ElementalC_Fij(n, i, j):
    E = np.eye(n)
    E[i,i], E[j,j] = 0, 0
    E[i,j], E[j,i] = 1, 1
    return E

def Elemental_Fi(n, i, k):
    E = np.eye(n)
    E[i,i] = k
    return E

def Elemental_Fij(n, i, j, k):
    E = np.eye(n)
    E[i,j] = k
    return E 

def findCero(A,i,j):
    p = -1
    for f in range(i,j):
        if (A[f][i-1]!=0):
            p = f
            break
    return p

def SustRegresiva(U,b):
    # Verificar si es triangular superior y cuadrado
    m,n = U.shape
    if m!=n:
        print("Proceso de Sustitucion Regresiva ERROR-[ Matriz no cuadrada ] ")
        return
    if np.array_equal(A, np.triu(A)):
        print("Proceso de Sustitucion Regresiva ERROR-[ Matriz no triangular superior ] ")
        return
    x = np.zeros(m)
    for i in range(m-1,-1,-1):
        suma = 0
        for j in range(i+1,n):
            suma += U[i][j]*x[j]
        x[i] = (b[i] - suma) / U[i][i]
    return x

def EliminacionGaussiana(A,b):
    m,n = A.shape
    M = np.concatenate((A,b), axis = 1 )
    E = [[A,b,M]]
    print(tabulate(E,headers=[["MATRIZ A"],["MATRIZ b"],["MATRIZ AUMENTADA"]],tablefmt='grid'))

    print("\t[+] ELIMINACION GAUSSEANA\n")       
    for i in range(m-1):
        pivote = M[i][i]
        print("Paso 1 : Hallando el pivote !=0")
        print("\t [+]Pivote   : {}".format(pivote))
        print("\t [+]Posicion : ({},{})".format(i,i))
        if pivote == 0:
            print("\t[-] Cambio de filas.")
            p = findCero(M,i+1,n) # Fila del nuevo pivote !=0
            if p == -1:
                print("No se encontro pivote Nulo.")
                return
            else:
                print("\t [+] Nuevo pivote: {}".format(M[p][i]))
                print("\t [+] Posicion : ({},{})".format(p,i))
                Fip = ElementalC_Fij(m,i,p)
                M_aux=M
                M = np.dot(Fip,M)
                pivote = M[i][i]
                h = ["Fip","M","Fip x M"]
                E = [[Fip,M_aux,M]]
                print(tabulate(E,headers=h,tablefmt='grid'))
                
        # Si no es diferente de cero Hacemos cero la columna
        print("Paso 2 : Las matrices elementales")
        header = ["Matriz Aumentada"]
        c=1
        E = [[M]]
        for j in range(i+1,m):
            factor = M[j][i]/pivote
            Fji = Elemental_Fij(m,j,i,-factor)            
            E[0].insert(0,np.copy(Fji))
            header.insert(0,"E"+str(c)+": F_{}{}({})".format(j,i,-factor))
            c+=1
            M = np.dot(Fji,M)
            
        print(tabulate(E,headers=header,tablefmt='grid'))
        print("Paso 3 : Haciendo (0) la columna C[{}]".format(i))
        print(M,"\n\n")
        
            
    U = M[:,:-1]
    b = M[:,-1:]
    x = SustRegresiva(U,b)
    h = ["U","b","Conjunto Solucion"]
    E = [[U,b,x.reshape(m,1)]]
    print("\t -> Por Sustitucion Regresiva")
    print(tabulate(E,headers=h,tablefmt='grid'))


In [ ]:
import numpy as np
A = np.array([
            [-1,3,-1,1],
            [1,-1,2,-1],
            [3,1,-2,2],
            [3,-1,1,2]
])
b = np.array([ 
                [-8],
                [4],
                [4],
                [16]
])
EliminacionGaussiana(A,b)

+-----------------+----------------+------------------------+
| ['MATRIZ A']    | ['MATRIZ b']   | ['MATRIZ AUMENTADA']   |
+=================+================+========================+
| [[-1  3 -1  1]  | [[-8]          | [[-1  3 -1  1 -8]      |
|  [ 1 -1  2 -1]  |  [ 4]          |  [ 1 -1  2 -1  4]      |
|  [ 3  1 -2  2]  |  [ 4]          |  [ 3  1 -2  2  4]      |
|  [ 3 -1  1  2]] |  [16]]         |  [ 3 -1  1  2 16]]     |
+-----------------+----------------+------------------------+
	[+] ELIMINACION GAUSSEANA

Paso 1 : Hallando el pivote !=0
	 [+]Pivote   : -1
	 [+]Posicion : (0,0)
Paso 2 : Las matrices elementales
+-----------------+-----------------+-----------------+--------------------+
| E3: F_30(3.0)   | E2: F_20(3.0)   | E1: F_10(1.0)   | Matriz Aumentada   |
+=================+=================+=================+====================+
| [[1. 0. 0. 0.]  | [[1. 0. 0. 0.]  | [[1. 0. 0. 0.]  | [[-1  3 -1  1 -8]  |
|  [0. 1. 0. 0.]  |  [0. 1. 0. 0.]  |  [1. 1. 0. 0.]  |  [ 1 

## Metodo de Gaus Jordan

In [ ]:
import numpy as np
from tabulate import tabulate

def ElementalC_Fij(n, i, j):
    E = np.eye(n)
    E[i,i], E[j,j] = 0, 0
    E[i,j], E[j,i] = 1, 1
    return E

def Elemental_Fi(n, i, k):
    E = np.eye(n)
    E[i,i] = k
    return E

def Elemental_Fij(n, i, j, k):
    E = np.eye(n)
    E[i,j] = k
    return E 

def findCero(A,i,j):
    p = -1
    for f in range(i,j):
        if (A[f][i-1]!=0):
            p = f
            break
    return p

def SustRegresiva(U,b):
    # Verificar si es triangular superior y cuadrado
    m,n = U.shape
    if m!=n:
        print("Proceso de Sustitucion Regresiva ERROR-[ Matriz no cuadrada ] ")
        return
    if np.array_equal(A, np.triu(A)):
        print("Proceso de Sustitucion Regresiva ERROR-[ Matriz no triangular superior ] ")
        return
    x = np.zeros(m)
    for i in range(m-1,-1,-1):
        suma = 0
        for j in range(i+1,n):
            suma += U[i][j]*x[j]
        x[i] = (b[i] - suma) / U[i][i]
    return x

def EliminacionGaussJordan(A,b):
    m,n = A.shape
    M = np.concatenate((A,b), axis = 1 )
    E = [[A,b,M]]
    print(tabulate(E,headers=[["MATRIZ A"],["MATRIZ b"],["MATRIZ AUMENTADA"]],tablefmt='grid'))

    print("\t[+] ELIMINACION POR GAUSS JORDAN\n")       
    for i in range(m):        
        pivote = M[i][i]
        print("Paso 1 : Hallando el pivote !=0")
        print("\t [+]Pivote   : {}".format(pivote))
        print("\t [+]Posicion : ({},{})".format(i,i))
        if pivote == 0:
            print("\t[-] Cambio de filas.")
            p = findCero(M,i+1,n) # Fila del nuevo pivote !=0
            if p == -1:
                print("No se encontro pivote Nulo.")
                return
            else:
                print("\t [+] Nuevo pivote: {}".format(M[p][i]))
                print("\t [+] Posicion : ({},{})".format(p,i))
                Fip = ElementalC_Fij(m,i,p)
                M_aux=M
                M = np.dot(Fip,M)
                pivote = M[i][i]
                h = ["Fip","M","Fip x M"]
                E = [[Fip,M_aux,M]]
                print(tabulate(E,headers=h,tablefmt='grid'))
        
        # luego tenemos que hacer 1 al pivote
        print("\t Luego Haciendo 1 al pivote : ")
        Fi = Elemental_Fi(m,i,1/pivote)
        M_aux=M
        M = np.dot(Fi,M)
        pivote = M[i][i]
        h = ["Fi","M","Fi x M"]
        E = [[Fi,M_aux,M]]
        print(tabulate(E,headers=h,tablefmt='grid'))
        
        
        # Si no es diferente de cero Hacemos cero la columna
        print("Paso 2 : Las matrices elementales")
        header = ["Matriz Aumentada"]
        c=1
        E = [[M]]
        for j in range(i+1,m):
            factor = M[j][i]/pivote
            Fji = Elemental_Fij(m,j,i,-factor)            
            E[0].insert(0,np.copy(Fji))
            header.insert(0,"E"+str(c)+": F_{}{}({})".format(j,i,-factor))
            c+=1
            M = np.dot(Fji,M)
        for j in range(i):
            factor = M[j][i]/pivote
            Fji = Elemental_Fij(m,j,i,-factor)            
            E[0].insert(0,np.copy(Fji))
            header.insert(0,"E"+str(c)+": F_{}{}({})".format(j,i,-factor))
            c+=1
            M = np.dot(Fji,M)
            
        
        print(tabulate(E,headers=header,tablefmt='grid'))
        print("Paso 3 : Haciendo (0) la columna C[{}]".format(i))
        print(M,"\n\n") 
                
    
    x = M[:,-1]    
    print("\t -> El conjunto solucion : ")
    print(x.reshape(n,1))
    

In [ ]:
import numpy as np
A = np.array([
            [-1,3,-1,1],
            [1,-1,2,-1],
            [3,1,-2,2],
            [3,-1,1,2]
])
b = np.array([ 
                [-8],
                [4],
                [4],
                [16]
])
EliminacionGaussJordan(A,b)

+-----------------+----------------+------------------------+
| ['MATRIZ A']    | ['MATRIZ b']   | ['MATRIZ AUMENTADA']   |
+=================+================+========================+
| [[-1  3 -1  1]  | [[-8]          | [[-1  3 -1  1 -8]      |
|  [ 1 -1  2 -1]  |  [ 4]          |  [ 1 -1  2 -1  4]      |
|  [ 3  1 -2  2]  |  [ 4]          |  [ 3  1 -2  2  4]      |
|  [ 3 -1  1  2]] |  [16]]         |  [ 3 -1  1  2 16]]     |
+-----------------+----------------+------------------------+
	[+] ELIMINACION POR GAUSS JORDAN

Paso 1 : Hallando el pivote !=0
	 [+]Pivote   : -1
	 [+]Posicion : (0,0)
	 Luego Haciendo 1 al pivote : 
+---------------------+--------------------+-------------------------+
| Fi                  | M                  | Fi x M                  |
+=====================+====================+=========================+
| [[-1.  0.  0.  0.]  | [[-1  3 -1  1 -8]  | [[ 1. -3.  1. -1.  8.]  |
|  [ 0.  1.  0.  0.]  |  [ 1 -1  2 -1  4]  |  [ 1. -1.  2. -1.  4.]  |
|  [ 0.  

## Factorizacion LDLT

In [3]:
import numpy as np
from tabulate import tabulate
def Sustitucion_directa(D, y):
    n = len(y)
    x = np.zeros(n)    
    for i in range(n):
        x[i] = y[i] / D[i][i]    
    return x

def SustitucionRegresivaU(U,b):    
    nfilas=np.shape(U)[0]
    ncolum=np.shape(U)[1]
    x=np.zeros(nfilas)    
    if nfilas!=ncolum:
        print("No es posible")
    for i in range(nfilas-1,-1,-1):
        x[i]=(b[i]-sum(U[i][k]*x[k] for k in range(i+1,nfilas)))/U[i][i]
    return x 
def SustitucionRegresivaL(L,b):
    nfilas=np.shape(L)[0]
    ncolum=np.shape(L)[1]
    x=np.zeros(nfilas)    
    if nfilas!=ncolum:
        print("No es posible")
    for i in range(nfilas):
        x[i]=(b[i]-sum(L[i][k]*x[k] for k in range(i-1,-1,-1)))/L[i][i]
    return x  

def imprimir_titulo(titulo):
    titulo_cent = titulo.center(50)
    print(f"\n{'='*50}\n{titulo_cent}\n{'='*50}")


    
def MatrizCuadrada(A):
    m,n = np.shape(A)
    if m!=n: # Si A no es cuadrada
        print(" -> [-] La Matriz A no es cuadrada.")
        return False
    else:   # Si A es cuadrada
        return True

    
det=["Determinate :"]
sub=[["Submatrices :"]]
def Regular(A):
    if MatrizCuadrada(A):
        n = np.shape(A[0])
        d = round(np.linalg.det(A),5)
        det.append(d)
        sub[0].append(A)
        if d==0:
            return False
        else:
            return True
    else:
        return False

def Simetrica(A):
    if MatrizCuadrada(A) and np.all(A.T == A):
        return True
    else:
        return False
        
    
def FactorizacionLDLt(A,b):
    '''
    Funcion que primero verifica si es posible factorizar la matriz A en 
    La forma LDL.T y retorna esas dos matrices L y D
    
    Parametros Posicionales:
    A -- Matriz cuadrada de coeficientes del sistema de ecuaciones a resolver
    b -- Vector columna del modelamiento Ax = b
    '''
    # Imprime el título centrado y con una línea debajo
    imprimir_titulo("FACTORIZACION LDL.T")
    print("A:\n",A,"\n---------------------------------------------------")
    # 1) Verificamos las Condiciones
    n = np.shape(A)[0]
    print(" 1) Verificamos si admite descomposicion LDM.T")
    for i in range(1,n+1):
        Sub_Matriz_Principal = A[:i,:i]
        if Regular(Sub_Matriz_Principal)==False:
            print("\t [-] No Admite descomposicion LDM.T")
            return False
    tabla = tabulate(sub, headers=det,  tablefmt='grid')
    print(tabla)
    print("\t [+] Submatrices de A son regulares.")
    print("\t [+] Admite descomposicion LDM.T")
    print("\n 2) Verificamos si es simetrica")
    if Simetrica(A)==False:
        print("\t [-] A no es simetrica")
        print("\t [-] No Admite descomposicion LDL.T")
        print("\t Multiplicamos por A.T :  A.T( Ax = b )   ")
        new_A = np.dot(A.T,A)
        new_b = np.dot(A.T,b)
        FactorizacionLDLt(new_A,new_b)       
        return False
    else:
        print("\t [+] A es simetrica")
        print("\t [+] Admite descomposicion LDL.T")
    print("\n 3) Hallamos el L y D")    
    L = np.zeros((n,n)) # L=0    
    D = np.zeros((n,n)) # D=0
    # LDLt
    L_list = []  # ahora es una lista vacía
    D_list = []  # ahora es una lista vacía
    i_list = []
    for i in range(n):       
        sum0 = sum([L[i][j]*L[i][j]*D[j][j] for j in range (i)])
        D[i][i] = A[i][i] - sum0

        for j in range(i, n):
            sum1 = sum([L[j][k]*L[i][k]*D[k][k] for k in range(i)])
            L[j][i] = (A[j][i] - sum1)/D[i][i]

        L_list.append(np.copy(L))  # copiamos la matriz L para almacenarla en la lista
        D_list.append(np.copy(D))  # copiamos la matriz D para almacenarla en la lista
        i_list.append(i)

    # Creamos la tabla con los datos y la imprimimos
    tabla = tabulate(zip(i_list, L_list, D_list), headers=['i', 'L', 'D'], tablefmt='grid')
    print(tabla)
    print("\n 4) A = LDL.T ")
    # Obtenemos la factorización LDL.T
    h= ['L', 'D','L.T']
    datos=[[L,D,L.T]]
    tabla = tabulate(datos, headers=h, tablefmt='grid')
    print(tabla)
    print("\n 5) Reemplazando  Ax=b -> (LDL.T)x = b\n ")
    print("[+] Aplicando sustitucion Regresiva L ->  L(DL.Tx) = b ") 
    y=SustitucionRegresivaL(L,b)    
    print(tabulate([["y",y.reshape(n,1)]], tablefmt='grid'))
    print("[+] Aplicando sustitucion Directa   D ->  D(L.Tx)  = y ")
    z=Sustitucion_directa(D, y)
    print(tabulate([["z",z.reshape(n,1)]], tablefmt='grid'))
    print("[+] Aplicando sustitucion Regresiva U ->  L.T(x)   = z ")
    x=SustitucionRegresivaU(L.T,z)
    
    print(tabulate([["x",x.reshape(n,1)]], tablefmt='grid'))
    h= ['y', 'z','x']
    datos=[[]]
    datos[0].append(y.reshape(n,1))
    datos[0].append(z.reshape(n,1))
    datos[0].append(x.reshape(n,1))
    print(tabulate(datos,headers=h, tablefmt='grid'))
    print("\n 6) Comprobamos :  ")
    LDLt = np.dot(np.dot(L,D),L.T)
    print("[+] LDL.T :\n", LDLt)
    if np.allclose(A, LDLt, rtol=1e-5):
        print("\n[+] La descomposición LDL.T es correcta.")        
    else:
        print("\n[-] La descomposición LDL.T es incorrecta.")
        return False

In [4]:
A = np.array([
    [1,2,4],    
    [4,4,1],
    [2,3,4]
])
b = np.array([
    [35],
    [34],
    [42]
])
FactorizacionLDLt(A,b)


               FACTORIZACION LDL.T                
A:
 [[1 2 4]
 [4 4 1]
 [2 3 4]] 
---------------------------------------------------
 1) Verificamos si admite descomposicion LDM.T
+-----------------+-------+---------+-----------+
| Determinate :   |   1.0 | -4.0    | 1.0       |
+=================+=======+=========+===========+
| Submatrices :   |     1 | [[1 2]  | [[1 2 4]  |
|                 |       |  [4 4]] |  [4 4 1]  |
|                 |       |         |  [2 3 4]] |
+-----------------+-------+---------+-----------+
	 [+] Submatrices de A son regulares.
	 [+] Admite descomposicion LDM.T

 2) Verificamos si es simetrica
	 [-] A no es simetrica
	 [-] No Admite descomposicion LDL.T
	 Multiplicamos por A.T :  A.T( Ax = b )   

               FACTORIZACION LDL.T                
A:
 [[21 24 16]
 [24 29 24]
 [16 24 33]] 
---------------------------------------------------
 1) Verificamos si admite descomposicion LDM.T
+-----------------+-------+---------+-----------+--------+-----

False

## Metodo de Cholesky

In [5]:
import numpy as np
from tabulate import tabulate
import math 
def Sustitucion_directa(D, y):
    n = len(y)
    x = np.zeros(n)    
    for i in range(n):
        x[i] = y[i] / D[i][i]    
    return x

def SustitucionRegresivaU(U,b):    
    nfilas=np.shape(U)[0]
    ncolum=np.shape(U)[1]
    x=np.zeros(nfilas)    
    if nfilas!=ncolum:
        print("No es posible")
    for i in range(nfilas-1,-1,-1):
        x[i]=(b[i]-sum(U[i][k]*x[k] for k in range(i+1,nfilas)))/U[i][i]
    return x 
def SustitucionRegresivaL(L,b):
    nfilas=np.shape(L)[0]
    ncolum=np.shape(L)[1]
    x=np.zeros(nfilas)    
    if nfilas!=ncolum:
        print("No es posible")
    for i in range(nfilas):
        x[i]=(b[i]-sum(L[i][k]*x[k] for k in range(i-1,-1,-1)))/L[i][i]
    return x  

def imprimir_titulo(titulo):
    titulo_cent = titulo.center(50)
    print(f"\n{'='*50}\n{titulo_cent}\n{'='*50}")


    
def MatrizCuadrada(A):
    m,n = np.shape(A)
    if m!=n: # Si A no es cuadrada
        print(" -> [-] La Matriz A no es cuadrada.")
        return False
    else:   # Si A es cuadrada
        return True
    
det=["Determinate :"]
sub=[["Submatrices :"]]
def DefinidaPositiva(A):
    if MatrizCuadrada(A):
        n = np.shape(A)[0]
        for i in range(1,n+1):
            subMatriz = A[:i,:i]
            d = round(np.linalg.det(subMatriz),5)
            det.append(d)
            sub[0].append(subMatriz)
            if d<=0:
                print("d = {} . No positivo ".format(d))
                return False
        return True
    else:
        return False
        
def Regular(A):
    if MatrizCuadrada(A):
        n = np.shape(A)[0]
        d = round(np.linalg.det(A),5)
        det.append(d)
        sub[0].append(A)
        if d==0:
            return False
        else:
            return True
    else:
        return False

def Simetrica(A):
    if MatrizCuadrada(A) and np.all(A.T == A):
        return True
    else:        
        return False

def MetodoCholesky(A,b):
    '''
    Funcion que verifica Si la matriz es definida positiva.Para luego hacer
    la descomposicion de Cholesky A = G.T(G); Donde G es triangular superior
    Tambien conocido como el descomposicion L(L.T)
    
    Parametros posicionales
    A -- matriz cuadrada que se desea descomponer
    '''
    n = np.shape(A)[0]
    
    imprimir_titulo("Metodo de Cholesky")
    tabla = tabulate([[A]], headers=["Matriz A"],  tablefmt='grid')
    print(tabla)
    #Verficamos que sea cuadrada y definida positiva
    print(" 1) Verificamos que sea Definida Positiva: ")
    condicion1 = DefinidaPositiva(A)
    condicion2 = Simetrica(A)
    if (condicion1): # Esta funcion ya verifica si es cuadrada
        tabla = tabulate(sub, headers=det,  tablefmt='grid')
        print(tabla)
        print("\t [+] A es definida positiva")
    else:
        tabla = tabulate(sub, headers=det,  tablefmt='grid')
        print(tabla)
        print("\t [-] No es definida positiva. Se encontro un determinante No positivo")
        print("\t [-] No admite factorizacion LDM.T")
       
    print("\n 2) Verificamos si es simetrica")
    if condicion2==False:
        print("\t [-] A no es simetrica")
        print("\t [-] No Admite descomposicion G(G.T) ; G es triangular superior")
        print("\t Multiplicamos por A.T :  A.T( Ax = b )   ")
        new_A = np.dot(A.T,A)
        new_b = np.dot(A.T,b)
        return MetodoCholesky(new_A,new_b)
        
    else:
        print("\t [+] A es simetrica")
    
    if (condicion1 and condicion2):
        print("\n\n 3) Luego : ")
        print(" -> [+] A es simetrica y definida Positva")
        print(" -> [+] A admite descomposicion G(G.T)")
        print("\n\n 4) Hallamos el G : ")
        G = np.zeros((n,n))
        G_list = []  # ahora es una lista vacía        
        i_list = []
        for i in range(n):
            # rellenamos la diagonal
            G[i,i] = math.sqrt(A[i,i]-sum([G[k,i]*G[k,i] for k in range(i)]))
            for j in range(i+1,n):
                # rellenamos los elementos por arriba
                G[i,j] = (A[i,j]-sum([G[k,i]*G[k,j] for k in range(i)]))/G[i,i]
            G_list.append(np.copy(G))  # copiamos la matriz L para almacenarla en la lista
            i_list.append(i)
        # Creamos la tabla con los datos y la imprimimos
        tabla = tabulate(zip(i_list, G_list), headers=['i', 'G'], tablefmt='grid')
        print(tabla)
        
        print("\n 5) A = G.T(G) o L(L.T) ")
        # Obtenemos la factorización LDL.T
        h= ['G.T','G']
        datos=[[G.T,G]]
        tabla = tabulate(datos, headers=h, tablefmt='grid')
        print(tabla)
        
        print("\n 6) A = G.T(G) ")        
        print(tabulate([[A,np.dot(G.T,G)]], headers=["A","G.T x  G "], tablefmt='grid'))
        
        print("\n 7) Hallamos la solucion : G.T(G) x = b ")    
        print("\n[+] Aplicando sustitucion Regresiva L ->  G.T(Gx) = b ") 
        y=SustitucionRegresivaL(G.T,b)    
        print(tabulate([["y",y.reshape(n,1)]], tablefmt='grid'))        
        
        print("[+] Aplicando sustitucion Regresiva U ->  G(x)   = y ")
        x=SustitucionRegresivaU(G,y)
        print(tabulate([["x",x.reshape(n,1)]], tablefmt='grid'))        
        return True
    else:
        print("\t [+] No es posible aplicar el Metodo de Cholesky")
        return False
    
    

In [6]:
A = np.array([
    [1,2,4],    
    [4,4,1],
    [2,3,4]
])
b = np.array([
    [35],
    [34],
    [42]
])
MetodoCholesky(A,b)


                Metodo de Cholesky                
+------------+
| Matriz A   |
+============+
| [[1 2 4]   |
|  [4 4 1]   |
|  [2 3 4]]  |
+------------+
 1) Verificamos que sea Definida Positiva: 
d = -4.0 . No positivo 
+-----------------+-------+---------+
| Determinate :   |   1.0 | -4.0    |
+=================+=======+=========+
| Submatrices :   |     1 | [[1 2]  |
|                 |       |  [4 4]] |
+-----------------+-------+---------+
	 [-] No es definida positiva. Se encontro un determinante No positivo
	 [-] No admite factorizacion LDM.T

 2) Verificamos si es simetrica
	 [-] A no es simetrica
	 [-] No Admite descomposicion G(G.T) ; G es triangular superior
	 Multiplicamos por A.T :  A.T( Ax = b )   

                Metodo de Cholesky                
+--------------+
| Matriz A     |
+==============+
| [[21 24 16]  |
|  [24 29 24]  |
|  [16 24 33]] |
+--------------+
 1) Verificamos que sea Definida Positiva: 
+-----------------+-------+---------+--------+-----------+-

True

## Metodo de Parlet Reid

In [1]:
import numpy as np
from tabulate import tabulate

def e(i,n):
    I=np.identity(n)
    return I[:,i-1:i]


def Fila_maximoElement(sub_matriz):
    n = np.shape(sub_matriz)[0] # Numero de filas
    ind = np.argmax(np.abs(sub_matriz))   
    return ind
        
def Formar_P(n,i_actual,j_maximo):
    I = np.identity(n)
    if(i_actual!=j_maximo):
        colum_actual  = I[:,i_actual:i_actual+1].copy()
        I[:,i_actual:i_actual+1]=I[:,j_maximo:j_maximo+1]
        I[:,j_maximo:j_maximo+1]=colum_actual
        return I
    else:
        return I

def FormarAlpha(Subcolumna):
    m,n = np.shape(Subcolumna)
    f_max = Fila_maximoElement(Subcolumna)   
    maximo = Subcolumna[f_max].copy()
    aux = Subcolumna[0].copy()
    for i in range(m):
        if(Subcolumna[i]==maximo):
            Subcolumna[i]=aux
            Subcolumna[0]=maximo
            break    
    for i in range(m):        
        Subcolumna[i]= Subcolumna[i]/maximo      
    
    return Subcolumna
    
def Formar_M(Subcolumna,i,n):
    I = np.identity(n)
    e = I[i:i+1,:]
    s = np.zeros((n,1))
    s_aux = FormarAlpha(Subcolumna)   
    s[i+1:,:]=s_aux[1:,:]
    
    print(" 3) Generamos M{}: I - alpha.e{}".format(i,i+1))
    print(tabulate([[I,s,e]],headers=["I","alpha","e"], tablefmt='grid')) 
    return I-np.dot(s,e)

def imprimir_titulo(titulo):
    titulo_cent = titulo.center(50)
    print(f"\n{'='*50}\n{titulo_cent}\n{'='*50}")
    
def ParletReit(A):
    imprimir_titulo("Metodo de Parlet Reid")
    n =  np.shape(A)[0]
    print(tabulate([["Matriz A",A]], tablefmt='grid'))  
    for i in range(n-2):
        print(" 1) Evaluamos la subcolumna:")
        Subcolumna = A[i+1:,i:i+1] 
        maximo = Fila_maximoElement(Subcolumna)
        print(tabulate([[A,Subcolumna,A[i,i+maximo+1]]],headers=["A","Subcolumna","maximo"], tablefmt='grid'))  
        P = Formar_P(n,i+1,i+maximo+1)
        print(" 2) Generamos P{}: e{} <-> e{}".format(i+1,i+2,i+maximo+2))
        print(tabulate([["P",P]], tablefmt='grid')) 
        M = Formar_M(Subcolumna.astype(float),i+1,n)
        print(" 4) Generamos M{}:".format(i+1))
        print(tabulate([["M",M]], tablefmt='grid')) 
        print(" 5) Hallamos el MP y MP.T :".format(i+1))
        MP = np.dot(M,P)
        MP_T = MP.T
        print(tabulate([[MP,MP_T]],headers=["MP","MP_T"], tablefmt='grid')) 
        print(" 6) Generamos el nuevo A({}):".format(i+1))
        A_aux=A.copy()
        A_aux = np.dot(MP,A_aux)
        A_aux = np.dot(A_aux,MP_T)
        A=A_aux
        print(tabulate([["MP(A{})MP.T".format(i+1),A]], tablefmt='grid')) 
        print()

In [2]:
A = np.array([
    [5,2,9,-6],
    [2,5,-6,9],
    [9,-6,5,2],
    [-6,9,2,5]
])
ParletReit(A)


              Metodo de Parlet Reid               
+----------+-----------------+
| Matriz A | [[ 5  2  9 -6]  |
|          |  [ 2  5 -6  9]  |
|          |  [ 9 -6  5  2]  |
|          |  [-6  9  2  5]] |
+----------+-----------------+
 1) Evaluamos la subcolumna:
+-----------------+--------------+----------+
| A               | Subcolumna   |   maximo |
+=================+==============+==========+
| [[ 5  2  9 -6]  | [[ 2]        |        9 |
|  [ 2  5 -6  9]  |  [ 9]        |          |
|  [ 9 -6  5  2]  |  [-6]]       |          |
|  [-6  9  2  5]] |              |          |
+-----------------+--------------+----------+
 2) Generamos P1: e2 <-> e3
+---+-----------------+
| P | [[1. 0. 0. 0.]  |
|   |  [0. 0. 1. 0.]  |
|   |  [0. 1. 0. 0.]  |
|   |  [0. 0. 0. 1.]] |
+---+-----------------+
 3) Generamos M1: I - alpha.e2
+-----------------+-----------------+-----------------+
| I               | alpha           | e               |
+=================+=================+=============